# Generated by Django 4.1.3 on 2023-02-17 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("cat_code", models.CharField(default="", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("dep_code", models.CharField(default="", max_length=20)),
                (
                    "head",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("asset", "Asset"),
                            ("accessory", "Accessory"),
                            ("consumable", "Consumable"),
                        ],
                        max_length=20,
                    ),
                ),
                ("item_name", models.CharField(max_length=300)),
                ("item_code", models.CharField(max_length=100)),
                ("price", models.PositiveIntegerField(default=0)),
                (
                    "currency",
                    models.CharField(blank=True, default="USD", max_length=20),
                ),
                ("quantity", models.PositiveIntegerField(blank=True, default=1)),
                ("quantity_unit", models.CharField(default="PCS", max_length=100)),
                ("min_alert_quantity", models.PositiveIntegerField(default=0)),
                (
                    "location",
                    models.CharField(blank=True, default="storage", max_length=100),
                ),
                (
                    "campus",
                    models.CharField(
                        choices=[
                            ("NAR", "Naryn"),
                            ("KHG", "Khorog"),
                            ("TKL", "Tekeli"),
                        ],
                        default="Naryn",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("vendor", models.CharField(blank=True, max_length=100)),
                ("date_received", models.DateField()),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("order_number", models.CharField(blank=True, max_length=100)),
                ("qr_code", models.CharField(blank=True, default="", max_length=200)),
                (
                    "image",
                    models.ImageField(default="items/default.png", upload_to="items"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("outinuse", "Out In Use"),
                            ("broken", "Broken"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="www.category",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="www.department"
                    ),
                ),
                (
                    "holder",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holder",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_id", models.CharField(max_length=20)),
                ("license_name", models.CharField(default="", max_length=100)),
                ("purchase_cost", models.PositiveIntegerField(default=0)),
                ("notification_days", models.PositiveIntegerField(default=3)),
                ("licensed_to", models.CharField(default="", max_length=100)),
                ("product_key", models.TextField(blank=True)),
                ("licensed_by", models.CharField(blank=True, max_length=100)),
                ("purchased_date", models.DateField(null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("order_number", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="www.department"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("location", models.CharField(max_length=100)),
                ("date", models.DateTimeField(auto_now=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="www.department"
                    ),
                ),
                (
                    "done_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item",
                        to="www.item",
                    ),
                ),
                (
                    "requestor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requestor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="www.department"
            ),
        ),
    ]
