# Generated by Django 4.1.3 on 2023-02-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0003_remove_item_holder_item_holder"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemassignment",
            name="action",
            field=models.CharField(
                choices=[("assign", "assign"), ("return", "return")],
                default="assign",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
