# Generated by Django 4.1.3 on 2023-04-12 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0006_itemhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemassignment",
            name="status",
            field=models.CharField(
                choices=[("in", "in"), ("out", "out")], default="in", max_length=3
            ),
        ),
    ]
