# Generated by Django 4.1.3 on 2023-04-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0007_itemassignment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
