# Generated by Django 4.1.3 on 2023-04-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0008_category_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
